### ISSUE TITLE
jpa support 

### ISSUE THREAD

**Issue by rodolfoliviero** [JoseRibeiro/jstryker#14]
today we support hibernate. Create a jpa helper so we'll support jpa too

**Comment by JoseRibeiro** [comment]
Now we have EntityManager using JPAHelper.
I'm thinking about read connection properties from persistence.xml.

**Comment by rodolfoliviero** [comment]
I opened another issue. See https://github.com/JoseRibeiro/jstryker/issues#issue/18

Done by this commit https://github.com/JoseRibeiro/jstryker/commit/7e021accf663eebe5e6b3aee211eb5f400026e87.
