### ISSUE TITLE
Disable HSQLDB referential integrity

### ISSUE THREAD

**Issue by JoseRibeiro** [JoseRibeiro/jstryker#16]
Create method to allow disable referential integrity on hsqldb database.
"SET DATABASE REFERENTIAL INTEGRITY FALSE"

**Comment by JoseRibeiro** [comment]
Set HSQLDB database referential integrity. Closed by 5ed3e739983f33192a93d94421d51ddd4b8462a6.

**Comment by gajarajkalburgi** [comment]
Below Query fails with ```integrity constraint violation: foreign key no action```.

```
CREATE TABLE A (
  A1 INT PRIMARY KEY,
  A2 VARCHAR(20)
);

CREATE TABLE B (
  B1 INT PRIMARY KEY ,
  B2 INT,
  FOREIGN KEY (B2) REFERENCES A(A1)
);

CREATE TABLE C (
  C1 INT PRIMARY KEY ,
  C2 INT,
  FOREIGN KEY (C2) REFERENCES B(B1)
);

INSERT INTO A VALUES (1, 'One');
INSERT INTO B VALUES (1, 1);
INSERT INTO C VALUES (1, 1);

SET DATABASE REFERENTIAL INTEGRITY FALSE;

TRUNCATE TABLE B;
TRUNCATE TABLE C;
TRUNCATE TABLE A;

SET DATABASE REFERENTIAL INTEGRITY TRUE;
```

But This works file.
```
CREATE TABLE A (
  A1 INT PRIMARY KEY,
  A2 VARCHAR(20)
);

CREATE TABLE B (
  B1 INT PRIMARY KEY ,
  B2 INT,
  FOREIGN KEY (B2) REFERENCES A(A1)
);

CREATE TABLE C (
  C1 INT PRIMARY KEY ,
  C2 INT,
  FOREIGN KEY (C2) REFERENCES B(B1)
);

INSERT INTO A VALUES (1, 'One');
INSERT INTO B VALUES (1, 1);
INSERT INTO C VALUES (1, 1);

SET DATABASE REFERENTIAL INTEGRITY FALSE;

DELETE FROM B;
DELETE FROM C;
DELETE FROM A;

SET DATABASE REFERENTIAL INTEGRITY TRUE;
```

**Comment by JoseRibeiro** [comment]
This is true, you can't truncate a table that has constraints to it. 
As far as I know, the reason is that truncate is a DDL command and can't validate the data being erased by it, that occasionally is referenced by a constraint in other table. 
The opposite occurs with delete command, that is a DML command and has to check for data being referenced by constraints in other tables.
